### ISSUE TITLE
'ts-node-script': No such file or directory

### ISSUE THREAD

**Issue by h4x3rotab** [l00k/devphase#1]
When installing devphase to a new project, I encountered the above error.

# Reproduce

```bash
yarn init
yarn add devphase
yarn devphase stack
```

Error message:

```
➜  phase-test yarn devphase stack
yarn run v1.22.15
$ /home/user/tmp/phase-test/node_modules/.bin/devphase stack
/usr/bin/env: 'ts-node-script': No such file or directory
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by h4x3rotab** [comment]
After doing the following setup, I can finally start devphase:

```
yarn add ts-node
yarn add typescript
yarn add tsconfig-paths
```

And then copy `tsconfig.json` and `devphase.config.ts` from [here](https://github.com/l00k/devphase-usage-sample) to the root dir

**Comment by l00k** [comment]
`tsconfig.json` doesn't contain anything interesting - it is just simple typescript config.
`devphase.config.ts` on the other hand it is required as it points project root dir.
`ts-node-script` is used as interpreter of entrypoint script, so I'm not sure. 
I will try to reproduce it, maybe some additional checks are required.

**Comment by h4x3rotab** [comment]
Sounds like a good idea to add a `yarn devphase init` command to init the project

**Comment by l00k** [comment]
Yeap. In general it is good idea and I will add it to todo list. However in this case it would not resolve issue. Cuz entrypoint of devphase executable is using `ts-node-script` as interpreter.

Ok found out. It is missing dependency (defined as peer).
It is `ts-node`. I didn't want to add it as direct dependency. I will think about it and give update.
![image](https://user-images.githubusercontent.com/29358909/199213269-01c493cb-a650-43f7-8118-f18361b9b434.png)

Thx.

**Comment by h4x3rotab** [comment]
Another way is to create a simple `devphase-up` script like `rustup` to do the dirty job.

**Comment by l00k** [comment]
Some dependencies adjusted in `^0.0.6`
Added info about required peer dependencies.

For now it is best solution IMO.
