### ISSUE TITLE
Auto stake to the contracts

### ISSUE THREAD

**Issue by h4x3rotab** [l00k/devphase#15]
In the Phat Contract tokenomic, every contract will need to have some stake in order to get the access to resources, including the CPU resource (for query) and RAM for local cache. Without staking, contract can still receive queries. It will just be put at the lowest scheduling priority. However it will get zero RAM for local cache, making the local cache unusable at all. When the contract uses the local cache, it will not be functional.

My suggestion is to add a small stake (e.g. 1 PHA) to all the contracts we instantiated like below:

```javascript
const stake = '1000000000000';
api.tx.phalaFatTokenomic.adjustStake(contract.address, stake);
```

**Comment by l00k** [comment]
Hmm.. I was sure it is enough to execute `phalaFatContracts.transferToCluster`.
At least it was working in my case.

Now it understand it is also required to adjust stake.
Thx.

**Comment by l00k** [comment]
Added in `v0.0.24`
