### ISSUE TITLE
Can not handle empty struct variants

### ISSUE THREAD

**Issue by tolak** [l00k/devphase#16]
Under the [current implementation](https://github.com/l00k/devphase/blob/67054e42d483e73c173b750f84e54ac42225d388/src/service/type-binding/StructTypeBuilder.ts#L255), we iterate the `variants` returned in metadata, but sometimes, the `variants` will not be iteraterable, e.g. it will be an empty object `{}`. For example, if we have an empty `Error` defined in ink contract:
```js
    #[derive(Encode, Decode, Debug, PartialEq, Eq)]
    #[cfg_attr(feature = "std", derive(scale_info::TypeInfo))]
    pub enum Error {
        // Empty, will lead to empty variants in metadata
    }
```
This will make the program crash, we should take care of it

**Comment by l00k** [comment]
Thx, Fixed in `v0.0.29`
