### ISSUE TITLE
Downloaded stack bin doesn't run on ubuntu

### ISSUE THREAD

**Issue by tp-go** [l00k/devphase#21]
The downloaded stack bin(phala-node, pruntime, pherry) doesn't run on ubuntu(22.04.1 LTS):

error:
```
[pruntime]
/mnt/d/workplace/paraxiom/devphase-usage-sample/stacks/nightly-2023-01-24/pruntime: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```

**Comment by l00k** [comment]
It seems good test for planned `check` command which will verify dependencies required to use devphase.
Atm I suggest you to verify libssl is properly installed in your system as suggested by output.

Btw. do I understand it right you are running it in WSL? It is good question does team tried running stack in WSL.
pruntime in dev mode should not use any SGX device however it may have other dependencies.
I tested latest release and it seems to work ok.

**Comment by h4x3rotab** [comment]
Here's a walkaround: <https://github.com/Phala-Network/phala-blockchain/issues/1142>

**Comment by l00k** [comment]
[#1143](https://github.com/Phala-Network/phala-blockchain/pull/1143)
According to this - next binary releases should not cause that issue.
