### ISSUE TITLE
Integrate with phala-blockchain-setup

### ISSUE THREAD

**Issue by h4x3rotab** [l00k/devphase#22]
Currently devphase has the ability to set up the local blockchain. However, compared with the official script [shelvenzhou/phala-blockchain-setup](https://github.com/shelvenzhou/phala-blockchain-setup), it lacks the SideVM log server and additional driver contracts. Having the log server can greatly simplify contract debugging.

**Comment by l00k** [comment]
Yes, absolutely.
That was in my plan but I didn't have time to implement it.
I think using code from this repo will help a lot.

**Comment by h4x3rotab** [comment]
Btw, this is how I integrate it manually in my config:

https://github.com/Phala-Network/phat-offchain-rollup/blob/2b79275a76829ad803b44038c1d76fe35272e637/phat/devphase.config.ts#L6-L54

**Comment by l00k** [comment]
Done, released in version `v0.1.4`
