### ISSUE TITLE
Decouple devphase CLI & Service into separate packages

### ISSUE THREAD

**Issue by HashWarlock** [l00k/devphase#26]
## Description
After speaking with @Leechael on how to best integrate `devphase` into `swanky` a recommendation to avoid dependencies without changing the core functionality of `devphase` would be decoupling the `devphase-cli` and `devphase-service` into separate packages. This allows for adding a plugin to `swanky` in a more sustainable way.
 
## Targets
![image](https://user-images.githubusercontent.com/64296537/221099190-58123e86-ee4d-4983-9916-c0ecd5fa0b21.png)
- [ ] Separate the 'service' component into a standalone package with no dependencies on `oclif`.
- [ ] The 'devphase/cli' package is for the CLI only, and acts as a glue layer between `oclif` and the `service` component.
- [ ] Since we have separated devphase into two packages, only the `devphase/cli` package should have a dependency on `oclif` v2. The `swanky-plugin-phala` can use `devphase/service` without declaring any dependencies on `oclif`.
- [ ] We can also implement a `dependency injection` design (if necessary) to further reduce boilerplate code.

**Comment by l00k** [comment]
Done.
Packages:
`@devphase/service: 0.0.1`
`@devphase/cli: 0.0.1`
