### ISSUE TITLE
Unable to use `devphase stack run` if version is different than `latest`

### ISSUE THREAD

**Issue by a-moreira** [l00k/devphase#30]
Opening the issue here as well because I think the problem might be either in this repo or in the `phat-offchain-rollup`:
https://github.com/Phala-Network/phat-offchain-rollup/issues/26

specs:
- Ubuntu 22.04
- nodejs 16.15.1
- yarn 1.22.19

**Comment by l00k** [comment]
@a-moreira 
Here you can find list of available releases:
https://github.com/Phala-Network/phala-blockchain/releases

First you need to ensure devphase and Phala binaries are compatible - it is ensured only for latest binaries and latest devphase.
In diffrent case - for example older Phala binaries release (which IMO should not be used) you need to find older devphase which was working with it.

Tested with example 'nightly-2023-05-26' - works fine
