### ISSUE TITLE
Work with cargo workspace

### ISSUE THREAD

**Issue by h4x3rotab** [l00k/devphase#5]
My contracts are developed within a cargo workspace, under `contracts/`. When compiling with devphase, I got this:

```
root@bca196224001:~/project# yarn devphase compile sample_oracle
[Compile] Contracts compilation
[MultiContractExecutor] Criteria: sample_oracle
[MultiContractExecutor] Matched contracts: [ 'sample_oracle' ]
[Compiler] Building: sample_oracle
# ....

Your contract artifacts are ready. You can find them in:
/root/project/target/ink/sample_oracle

  - sample_oracle.contract (code + metadata)
  - sample_oracle.wasm (the contract's code)
  - metadata.json (the contract's metadata)
[Compiler] File /root/project/contracts/sample_oracle/target/ink/sample_oracle.contract not generated
/root/project/node_modules/devphase/dist/cli/index.js:238
            throw new Exception(`Unable to execute action for ${contract} contract`, 1667022951192);
                  ^
Throwable: Unable to execute action for sample_oracle contract
    at MultiContractExecutor.exec (/root/project/node_modules/devphase/dist/cli/index.js:238:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 1667022951192
}
error Command failed with exit code 1.
```

`cargo` outputs the target in different places if it's in a workspace or not:

- Non-workspace: `$PROJECT/contracts/$CONTRACT/target/ink`
- Workspace: `$PROJECT/target/ink/$CONTRACT`

Currently devphase only recognize the first case. We should support the workspace as well.

**Comment by h4x3rotab** [comment]
Now I'm using a soft symlink to point `target/ink` to the space output dir. I suggest to detect if the `cargo.toml` file has the workspace enabled in the project root.

**Comment by l00k** [comment]
On the other hand it is also possible to specify different target directory.
For now I will detect output directory and copy `artifacts` to separate directory (which may be also useful).

^0.0.12

**Comment by h4x3rotab** [comment]
I confirm it works now
