### ISSUE TITLE
Handle trait definitions in TypeBind

### ISSUE THREAD

**Issue by h4x3rotab** [l00k/devphase#6]
The current type generator doesn't handle trait definitions.

Normally, if a contract `ContractA` has a tx method `func1`, we call it by:

```javascript
const a = new ContractPromise(api, metadata, address);
await a.tx.func1().signAndSubmit(...);
```

However if `ContractA` implements a trait definition (`TraitX`) that implements a tx method `trait_x_func2`, it must be called by:

```javascript
const a = new ContractPromise(api, metadata, address);
await a.tx['traitX::traitXFunc2']().signAndSubmit(...);
```

(Note that the key is also converted to camelCase)

For the trait definition, here's the generate metadata as a reference:

```json
        {
          "args": [],
          "docs": [],
          "label": "TraitX::trait_x_func2",
          "mutates": false,
          "payable": false,
          "returnType": {
            "displayName": [
              "core",
              "result",
              "Result"
            ],
            "type": 9
          },
          "selector": "0xABCDABCD"
        }
```

**Comment by l00k** [comment]
Implemented in ^0.0.15
