### ISSUE TITLE
Generate CamelCase instead of Camel_case contract type bindings

### ISSUE THREAD

**Issue by h4x3rotab** [l00k/devphase#7]
https://github.com/l00k/devphase/blob/21f4f79978913321e61a53eae59ed9a7abc69101/src/service/project/TypeBinder.ts#L65

We may change it to `upperFirst(camelCase(metadata.contract.name))` to produce CamelCase files names.

**Comment by l00k** [comment]
Absolutely agreed! 
Will be implemented in ^0.0.12
