### ISSUE TITLE
Suggest to add an option to output the full stack log to the file

### ISSUE THREAD

**Issue by h4x3rotab** [l00k/devphase#9]
When running `devphase stack` everything is on the screen. I can redirect it to a file for debugging like this:

```bash
yarn devphase stack |& tee tmp/stack.log
```

However when running e2e test, it will be hard to get the output. This is especially useful when debugging with some weird case (e.g. wasm contains float point operations, causing the code rejected by pruntime).

**Comment by h4x3rotab** [comment]
It's a low priority feature request though

**Comment by l00k** [comment]
Done in ^0.0.13
